name: "Recipe"
type: "item"
data:
  description: "<p>A complicated recipe.</p>"
  esoteric: false
  quantity: 1
img: "/systems/dee/assets/default/icons/kit.png"
permission:
    default: 2
folder: "Printed Matter"